name: vendor
description: "Vendor App."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  vtv_common:
    path: ../vtv_common
  flutter:
    sdk: flutter

  # ui
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.9
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.1.0
  timelines: ^0.1.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^25.2.5

  # navigation + state management
  go_router: ^13.0.1
  flutter_bloc: ^8.1.3

  # storage
  image_picker: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # notification
  firebase_messaging: ^14.7.17
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.25.4
  fluttertoast: ^8.2.4

  # functional
  intl: ^0.19.0
  dartz: ^0.10.1
  provider: ^6.1.1
  get_it: ^7.6.7
  equatable: ^2.0.5
  jwt_decoder: ^2.0.1
  collection:

  # network
  http: ^1.2.0
  dio: ^5.4.2+1
  connectivity_plus: ^6.0.1
  http_parser: ^4.0.2
  # retry: ^3.1.2

  # dev
  logger: ^2.0.2+1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  # activated in the `analysis_options.yaml` file.
  flutter_lints: ^3.0.1

# following page: https://dart.dev/tools/pub/pubspec
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/
    - assets/images/
    - assets/images/placeholders/
    - assets/svg/
    - assets/icons/
